apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: sysdigcloud-elasticsearch
  labels:
    app: sysdigcloud
    role: elasticsearch
spec:
  serviceName: sysdigcloud-elasticsearch
  podManagementPolicy: "OrderedReady"
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: sysdigcloud
      role: elasticsearch
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: elasticsearch
    spec:
      terminationGracePeriodSeconds: 120
      containers:
        - name: elasticsearch
          image: quay.io/sysdig/elasticsearch:5.1.1.0
          # https://www.elastic.co/blog/bootstrap_checks_annoying_instead_of_devastating
          # Elasticsearch team decided to force everybody to run ES5 with the following sysctl option:
          # sysctl -w vm.max_map_count=262144
          # If you choose to run the container in privileged mode the container will automatically configured the system
          # parameter and start elasticsearch as elasticsearch user.
          # if you choose to run the container not in privileged mode make sure to configure the vm.max_map_count
          # on all the servers of your cluster
          securityContext:
            privileged: true
          env:
            - name: ELASTICSEARCH_SERVICE
              value: sysdigcloud-elasticsearch
            - name: ELASTICSEARCH_GOSSIP_NODES_NUM
              value: "2"
            - name: ELASTICSEARCH_CLUSTER_NAME
              value: sysdigcloud
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: elasticsearch.jvm.options
          volumeMounts:
            - name: data
              mountPath: /usr/share/elasticsearch/data
      imagePullSecrets:
        - name: sysdigcloud-pull-secret
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # Uncomment this for AWS Disk
      #storageClassName: sysdigcloud-cassandra-sc-aws
      # Uncomment this for GCE Disk
      storageClassName: sysdigcloud-cassandra-sc-gce
      resources:
        requests:
          # We reccomend 1G of disk space for each connected agent
          storage: 100Gi