apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: sysdigcloud-redis
  labels:
    app: sysdigcloud
    role: redis
spec:
  serviceName: sysdigcloud-redis
  podManagementPolicy: "OrderedReady"
  updateStrategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: sysdigcloud
      role: redis
  template:
    metadata:
      labels:
        app: sysdigcloud
        role: redis
    spec:
      containers:
        - name: redis
          image: quay.io/sysdig/redis:2.8.23
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: sysdigcloud-config
                  key: redis.password
      imagePullSecrets:
        - name: sysdigcloud-pull-secret